# Generated by Django 5.2.6 on 2026-08-22 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(default='technical', max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('topic', models.CharField(default='', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('hints', models.JSONField(default=list)),
                ('expected_points', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InterviewAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField()),
                ('ai_feedback', models.TextField(default='')),
                ('score', models.FloatField(default=0.0)),
                ('strengths', models.JSONField(default=list)),
                ('improvements', models.JSONField(default=list)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='interviews.interviewquestion')),
            ],
            options={
                'ordering': ['question__order'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('technical', 'Technical'), ('behavioral', 'Behavioral'), ('system_design', 'System Design'), ('mixed', 'Mixed')], default='technical', max_length=20)),
                ('total_questions', models.PositiveIntegerField(default=5)),
                ('completed_questions', models.PositiveIntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('target_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_sessions', to='skills.jobrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interviews.interviewsession'),
        ),
    ]
