# Generated by Django 5.2.6 on 2026-08-22 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('remote', 'Remote')], default='full_time', max_length=20)),
                ('description', models.TextField(default='')),
                ('requirements', models.JSONField(default=list)),
                ('salary_min', models.PositiveIntegerField(default=0)),
                ('salary_max', models.PositiveIntegerField(default=0)),
                ('url', models.URLField(blank=True, default='')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='JobRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=0.0)),
                ('matching_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('recommended_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-match_score'],
                'unique_together': {('user', 'job')},
            },
        ),
    ]
