# Generated by Django 5.2.6 on 2026-08-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(blank=True, default='1-3 Yrs Exp', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='posted_time_text',
            field=models.CharField(blank=True, default='Just now', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_display',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='source',
            field=models.CharField(blank=True, default='LinkedIn', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='work_mode',
            field=models.CharField(blank=True, default='On-site', max_length=50),
        ),
    ]
